# Ejercicio 3
## Enunciado
Un agente comercial realiza su trabajo en tres ciudades A, B y C. Para evitar desplazamientos innecesarios está todo el día en la misma ciudad y allí pernocta, desplazándose a otra ciudad al día siguiente, si no tiene suficiente trabajo. Después de estar trabajando un día en C, la probabilidad de tener que seguir trabajando en ella al día siguiente es 0,4, la de tener que viajar a B es 0,4 y la de tener que ir a A es 0,2. Si el viajante duerme un día en B, con probabilidad de un 20% tendrá que seguir trabajando en la misma ciudad al día siguiente, en el 60% de los casos viajará a C, mientras que irá a A con probabilidad 0,2. Por último si el agente comercial trabaja todo un día en A, permanecerá en esa misma ciudad, al día siguiente, con una probabilidad 0,1, irá a B con una probabilidad de 0,3 y a C con una probabilidad de 0,6.

* Ejercicio A: Si hoy el viajante está en C, ¿cuál es la probabilidad de que también tenga que trabajar en C al cabo de cuatro días?
* Ejercicio B: ¿Cuáles son los porcentajes de días en los que el agente comercial está en cada una de las tres ciudades?

In [162]:
# Importamos las librerías que vamos a usar:
import numpy as np

Ingresamos los datos de la matriz de transición en una matriz numpy:

In [163]:
T = np.array([[0.1, 0.3, 0.6],
              [0.2, 0.2, 0.6],
              [0.2, 0.4, 0.4]])
print(T)

[[0.1 0.3 0.6]
 [0.2 0.2 0.6]
 [0.2 0.4 0.4]]


## Ejercicio A
* Calculamos la matriz de transición habiendo pasado 4 días. Elevamos la matriz a la cuarta usando el método de la potencia de álgebra lineal de la librería numpy.

* Sabiendo que $p_0$ considera que el agente está en el nodo C:
$ p_0 = (0, 0, 1) $

* Calculamos:
$ p_0 T^4 = p_4 $

* Dado el vector $ p_4 $, nos quedamos con el componente perteneciente al estado C.

In [164]:
# Ejercicio A

# Cálculo de la matriz de transición a tiempo 4:
T4 = np.linalg.matrix_power(T, 4)
print('** Matriz de transición a tiempo 4: \n %s' % T4)

# Generación del vector inicial p_0:
p_0 = np.array([0, 0, 1])
print('\n ** Vector de estado a tiempo 0: \n %s' % p_0)

# Cálculo del estado a tiempo 4, p_4:
p_4 = np.dot(p0, T4)
print('\n ** Vector de estado a tiempo 4: \n %s' % p_4)

# Componente del nodo C:
p_4_c = p_4[2]
print('\n ** Probabilidad de estar en c habiendo iniciado en c: \n %.5f' % p_4_c)

** Matriz de transición a tiempo 4: 
 [[0.1819 0.3189 0.4992]
 [0.1818 0.319  0.4992]
 [0.1818 0.3174 0.5008]]

 ** Vector de estado a tiempo 0: 
 [0 0 1]

 ** Vector de estado a tiempo 4: 
 [0.1818 0.3174 0.5008]

 ** Probabilidad de estar en c habiendo iniciado en c: 
 0.50080


### Forma alternativa de resolución:
El resultado es el mismo si consideramos que la componente ${T^4}_{cc}$ es la probabilidad de transición del nodo c al mismo nodo habiendo pasado 4 ciclos.
Veamos cómo se obtiene esa componente:

In [165]:
# Componente de cc de la matriz de transición a tiempo 4:
T4cc = T4[2,2]
print('\n ** Probabilidad de estar en c habiendo iniciado en c: \n %.5f' % T4cc)


 ** Probabilidad de estar en c habiendo iniciado en c: 
 0.50080


## Ejercicio B
Dada una matriz $A$ proveniente del sistema de ecuaciones que resuelve $\pi T = \pi$

Y dado un vector $B$ relacionado con los términos independientes del sistema de ecuaciones anteriormente mencionado.

Estos vectores fueron calculados a mano anteriormente, procedemos a cargarlos:

In [166]:
# Matriz A:
A = np.array([[-0.9,  0.2,  0.2],
              [ 0.3, -0.8,  0.4],
              [ 0.6,  0.6, -0.6],
              [1, 1, 1]])

print('\n ** Matriz asociada al sistema lineal de ecuaciones: \n %s' % A)

# Vector B:
B = np.array([0, 0, 0, 1])
print('\n ** Vector de términos independientes: \n %s' % B)


 ** Matriz asociada al sistema lineal de ecuaciones: 
 [[-0.9  0.2  0.2]
 [ 0.3 -0.8  0.4]
 [ 0.6  0.6 -0.6]
 [ 1.   1.   1. ]]

 ** Vector de términos independientes: 
 [0 0 0 1]


Dado que el solver de numpy solamente admite sistemas lineales cuadrados por el algoritmo que usa para la resolución [1], debemos eliminar una de las filas (cualquiera) de la matriz homogénea y quedarnos con la fila relacionada a la ecuación $ \sum_i{\pi_i} = 1$.
Hacemos lo mismo para el vector de términos independientes.

Para hacer esto usamos la función el método delete de numpy, indicando la posición a eliminar y el eje (axis) al que pertenece.


[1] https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.linalg.solve.html

In [167]:
# Eliminamos la primer fila de la matriz A:
A = np.delete(A, 0, 0)
A_dim = A.shape
print('\n ** Matriz asociada al sistema lineal de ecuaciones: \n %s' % A)
print('\n -> Dimensión: %s' % str(A_dim))

# Eliminamos la primera componente del vector B:
B = np.delete(B, 0, 0)
B_dim = B.shape
print('\n ** Vector de términos independientes: \n %s' % B)
print('\n -> Dimensión: %s' % str(B_dim))


 ** Matriz asociada al sistema lineal de ecuaciones: 
 [[ 0.3 -0.8  0.4]
 [ 0.6  0.6 -0.6]
 [ 1.   1.   1. ]]

 -> Dimensión: (3, 3)

 ** Vector de términos independientes: 
 [0 0 1]

 -> Dimensión: (3,)


Cumpliendo con un sistema cuadrado, usamos el método solve de numpy para obtener $x$ del sistema $Ax = B$

In [168]:
x = np.linalg.solve(A, B)
print('\n ** Vector solución de estado estable: \n %s' % x)


 ** Vector solución de estado estable: 
 [0.18181818 0.31818182 0.5       ]


### Forma alternativa: usando una matriz no cuadrada
Como explicamos anteriormente no podemos usar el método $solve$ en matrices no cuadradas. En su lugar podemos usar el método de los mínimos cuadrados para aproximar la solución[2]. Este método no tiene restricciones en cuanto a la dimensión de la matriz.

El desarrollo del método no forma parte de la materia, siendo contenido de Análisis Numérico y Cálculo Avanzado.

[2] https://docs.scipy.org/doc/numpy/reference/generated/numpy.linalg.lstsq.html

In [169]:
x_lstsq, _, _, _ = np.linalg.lstsq(A, B, rcond=None)
print('\n ** Vector solución de estado estable: \n %s' % x_lstsq)


 ** Vector solución de estado estable: 
 [0.18181818 0.31818182 0.5       ]


### Cálculo auxiliar: partiendo directamente de la matriz de transición
En la resolución original, usamos una matriz A relacionada al sistema lineal de ecuaciones que resolvimos a mano. Ahora veremos otra forma de llegar a la solución solamente con los datos dados y tratamiento de matrices.

Partiendo del sistema original: $\pi T = \pi$

Despejando $\pi$ obtenemos:

$(T^T - I) \pi^T = 0 $

Podemos transformar lo anterior en la notación que usamos más arriba para que tenga consistencia:

$A = (T^T - I)$

$X = \pi^T$

$B = 0$

Por lo tanto, llegamos a la misma expresión $Ax = B$

In [170]:
# Primero calculamos la traspuesta:
Tt = np.transpose(T)
print('\n ** T traspuesta: \n %s' % Tt)

# Luego con calculamos la matriz A, sabiendo que es la traspuesta de T menos la identidad.
A = Tt - np.identity(Tt.shape[0])
print('\n ** Matriz A: \n %s' % A)

# El vector B, es un vector de ceros:
B = np.zeros(3)
print('\n ** Vector B: \n %s' % B)


 ** T traspuesta: 
 [[0.1 0.2 0.2]
 [0.3 0.2 0.4]
 [0.6 0.6 0.4]]

 ** Matriz A: 
 [[-0.9  0.2  0.2]
 [ 0.3 -0.8  0.4]
 [ 0.6  0.6 -0.6]]

 ** Vector B: 
 [0. 0. 0.]


Teniendo lo anterior agregamos la condición de sumatoria de probabilidades igual a 1 y resolvemos con mínimos cuadrados:

In [171]:
# Primero calculamos la traspuesta:
eq_suma_p = np.array([[1, 1, 1]])
A = np.concatenate((A, eq_suma_p), axis=0)
print('\n ** Matriz A: \n %s' % A)

# El vector B, es un vector de ceros:
B = np.append(B, 1)
print('\n ** Vector B: \n %s' % B)

# Resolvemos con método de mínimos cuadrados:
x_lstsq, _, _, _ = np.linalg.lstsq(A, B, rcond=None)
print('\n ** Vector solución de estado estable: \n %s' % x_lstsq)


 ** Matriz A: 
 [[-0.9  0.2  0.2]
 [ 0.3 -0.8  0.4]
 [ 0.6  0.6 -0.6]
 [ 1.   1.   1. ]]

 ** Vector B: 
 [0. 0. 0. 1.]

 ** Vector solución de estado estable: 
 [0.18181818 0.31818182 0.5       ]
